"""Initial Migration

Revision ID: 1365722e6925
Revises: 91e9dbd1aefe
Create Date: 2022-03-09 16:18:32.512877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1365722e6925'
down_revision = '91e9dbd1aefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pitches_category', table_name='pitches')
    op.drop_index('ix_pitches_description', table_name='pitches')
    op.drop_index('ix_pitches_title', table_name='pitches')
    op.drop_index('ix_pitches_username', table_name='pitches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pitches_username', 'pitches', ['username'], unique=False)
    op.create_index('ix_pitches_title', 'pitches', ['title'], unique=False)
    op.create_index('ix_pitches_description', 'pitches', ['description'], unique=False)
    op.create_index('ix_pitches_category', 'pitches', ['category'], unique=False)
    # ### end Alembic commands ###
