"""Initial Migration

Revision ID: 918036e8232c
Revises: 4294397f54fd
Create Date: 2022-03-08 10:45:21.235750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918036e8232c'
down_revision = '4294397f54fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
