"""Initial Migration

Revision ID: 91e9dbd1aefe
Revises: 98411b88814f
Create Date: 2022-03-09 16:12:53.723318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e9dbd1aefe'
down_revision = '98411b88814f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_id_key', 'pitches', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pitches_id_key', 'pitches', ['id'])
    # ### end Alembic commands ###
