"""Initial Migration

Revision ID: 98411b88814f
Revises: 
Create Date: 2022-03-09 16:06:32.444572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98411b88814f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pitches', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='unique')
    # ### end Alembic commands ###
